"""Initial migration

Revision ID: 9565b38ca101
Revises: 
Create Date: 2024-12-02 10:39:04.372753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9565b38ca101'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encrypted_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_file', sa.Text(), nullable=True))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encrypted_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', mysql.TEXT(), nullable=False))
        batch_op.drop_column('encrypted_file')
        batch_op.drop_column('encrypted_text')

    # ### end Alembic commands ###
